title = "Tigo CTM"
baseurl = "http://tigoctm.com/"
publishdir = "public"
contentdir = "src/hugo/content"
layoutdir = "src/hugo/layouts"
staticdir = "src/hugo/static"
themesdir = "src/hugo/themes"
languageCode = "en-US"

[params]
  # Meta parameters.
  language = "en"
  encoding = "utf-8"
  description = ""

[blackfriday]
  hrefTargetBlank = true

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
